"""Seed catalog: question bank, role blueprints, plans, companies. Admins can edit all of it later."""

# (category, topic, role_family, difficulty, text, ideal_points)
QUESTIONS: list[tuple[str, str, str, int, str, list[str]]] = [
    # ---------------- Frontend
    ("technical", "JavaScript Event Loop", "frontend", 3,
     "Explain how the JavaScript event loop works. In what order do setTimeout, Promise.then and synchronous code run?",
     ["call stack executes synchronous code first", "microtask queue (promises) drains before macrotasks",
      "macrotask queue holds timers and I/O callbacks", "rendering happens between macrotasks"]),
    ("technical", "JavaScript Closures", "frontend", 2,
     "What is a closure in JavaScript? Give a practical use case and one pitfall.",
     ["function retains access to its lexical scope", "used for data privacy or factories",
      "classic pitfall with var in loops", "can cause memory leaks if references are kept"]),
    ("technical", "React Rendering", "frontend", 3,
     "What triggers a re-render in React, and how would you prevent unnecessary re-renders?",
     ["state or props change triggers re-render", "parent re-render re-renders children by default",
      "React.memo, useMemo, useCallback", "keys and stable references", "profile with React DevTools"]),
    ("technical", "React Hooks", "frontend", 3,
     "How does useEffect work, and what are the common mistakes with its dependency array?",
     ["runs after render and commit", "dependency array controls re-execution",
      "stale closures from missing deps", "cleanup function prevents leaks", "avoid effects for derived state"]),
    ("technical", "TypeScript Types", "frontend", 3,
     "What is the difference between `type` and `interface` in TypeScript, and when would you use generics?",
     ["interfaces can be merged and extended", "type aliases support unions and mapped types",
      "generics provide reusable type-safe abstractions", "constraints with extends"]),
    ("technical", "Browser Rendering", "frontend", 4,
     "Walk me through what happens from typing a URL to seeing pixels on the screen.",
     ["DNS lookup and TCP/TLS handshake", "HTTP request and response", "HTML parsed into DOM, CSS into CSSOM",
      "render tree, layout, paint, composite", "blocking scripts and resource loading"]),
    ("technical", "Web Performance", "frontend", 4,
     "A page has poor LCP and INP scores. How do you diagnose and fix it?",
     ["measure with Lighthouse or Web Vitals in the field", "optimize images and critical resources for LCP",
      "reduce main-thread work and long tasks for INP", "code splitting and lazy loading", "caching and CDN"]),
    ("technical", "CSS Layout", "frontend", 2,
     "When would you choose Flexbox versus CSS Grid? Give an example of each.",
     ["flexbox is one-dimensional", "grid is two-dimensional", "flexbox for alignment of components",
      "grid for page layouts"]),
    ("technical", "Next.js Rendering", "frontend", 4,
     "Compare SSR, SSG, ISR and client-side rendering in Next.js. How do you choose between them?",
     ["SSR renders per request", "SSG renders at build time", "ISR revalidates static pages",
      "server components reduce client JS", "trade-off between freshness, cost and speed"]),
    ("architecture", "Frontend Architecture", "frontend", 4,
     "How would you structure state management in a large React application?",
     ["separate server state from client state", "use a query cache for server state",
      "local state by default, lift only when needed", "avoid a single global store for everything"]),
    # ---------------- Backend
    ("technical", "Database Indexing", "backend", 3,
     "How do database indexes work, and when can an index make things worse?",
     ["B-tree structure enables logarithmic lookup", "speeds reads on filtered or sorted columns",
      "slows writes and uses storage", "composite index column order matters", "use EXPLAIN to verify"]),
    ("technical", "SQL Transactions", "backend", 3,
     "Explain ACID and transaction isolation levels. What anomalies does each level prevent?",
     ["atomicity consistency isolation durability", "read committed prevents dirty reads",
      "repeatable read prevents non-repeatable reads", "serializable prevents phantoms",
      "trade-off between consistency and throughput"]),
    ("technical", "Caching", "backend", 3,
     "How would you add caching to a slow API endpoint? How do you handle invalidation?",
     ["cache-aside pattern", "TTL and explicit invalidation on writes", "cache key design",
      "thundering herd and stampede protection", "consistency trade-offs"]),
    ("technical", "REST API Design", "backend", 2,
     "What makes a good REST API? How do you handle versioning, pagination and errors?",
     ["resource-oriented URLs and HTTP verbs", "correct status codes", "pagination with cursor or offset",
      "versioning strategy", "idempotency for retries"]),
    ("technical", "Concurrency", "backend", 4,
     "What is the difference between concurrency and parallelism? How do you avoid race conditions?",
     ["concurrency is structure, parallelism is execution", "race conditions on shared state",
      "locks, atomic operations, or message passing", "deadlocks and how to avoid them"]),
    ("technical", "Message Queues", "backend", 4,
     "When would you introduce a message queue? What delivery guarantees exist?",
     ["decouple producers and consumers", "absorb load spikes", "at-most-once, at-least-once, exactly-once",
      "idempotent consumers", "dead letter queues and retries"]),
    ("technical", "Python Internals", "backend", 3,
     "Explain the GIL in Python. How does it affect multithreading and what are the alternatives?",
     ["GIL allows one thread to execute bytecode at a time", "threads still help with I/O-bound work",
      "multiprocessing for CPU-bound work", "asyncio for high-concurrency I/O"]),
    ("technical", "Authentication", "backend", 3,
     "How would you implement authentication for a web API? Compare sessions and JWT.",
     ["password hashing with bcrypt or argon2", "server-side sessions are revocable",
      "JWT are stateless but hard to revoke", "httpOnly secure cookies", "refresh tokens and expiry"]),
    ("debugging", "Production Debugging", "backend", 3,
     "An endpoint's p99 latency jumped from 200ms to 3s after a deploy. How do you investigate?",
     ["check metrics and traces to localize the slowdown", "compare with the deploy diff",
      "check database slow queries and locks", "consider rollback to mitigate", "write a postmortem"]),
    # ---------------- System design (any engineering)
    ("system_design", "URL Shortener", "any", 3,
     "Design a URL shortener like bit.ly. Start with requirements.",
     ["clarify functional and non-functional requirements", "estimate traffic and storage",
      "ID generation strategy (base62, counter, hash)", "read-heavy caching", "database choice and partitioning",
      "analytics and expiration"]),
    ("system_design", "Food Delivery System", "any", 4,
     "Design a food delivery platform like Glovo or Wolt for a city of 2 million people.",
     ["clarify actors: customers, restaurants, couriers", "order lifecycle and state machine",
      "courier location updates and matching", "payments and idempotency", "notifications and queues",
      "scaling hot regions and peak hours"]),
    ("system_design", "Payment System", "any", 5,
     "Design a payment processing system. How do you guarantee money is never charged twice?",
     ["idempotency keys", "double-entry ledger", "state machine for payment status",
      "reconciliation with providers", "exactly-once effects via outbox pattern", "audit and security"]),
    ("system_design", "Chat System", "any", 4,
     "Design a real-time chat like Telegram for one-to-one and group messages.",
     ["websockets or long polling", "message storage and ordering", "delivery and read receipts",
      "fan-out for groups", "presence service", "offline sync and push notifications"]),
    ("system_design", "Rate Limiter", "any", 3,
     "Design a distributed rate limiter for a public API.",
     ["token bucket or sliding window", "where to enforce: gateway or service", "shared counter in Redis",
      "race conditions and atomic operations", "response headers and 429 semantics"]),
    # ---------------- Coding (verbal approach in MVP)
    ("coding", "Arrays and Hashing", "any", 2,
     "Given an array of integers and a target, return the indices of two numbers that add up to the target. Describe your approach and its complexity.",
     ["brute force is O(n^2)", "hash map of value to index", "single pass O(n) time", "O(n) extra space",
      "edge cases: duplicates, no solution"]),
    ("coding", "Sliding Window", "any", 3,
     "Find the length of the longest substring without repeating characters. Explain the algorithm and complexity.",
     ["sliding window with two pointers", "set or map of last seen index", "move left pointer on repeat",
      "O(n) time", "edge cases: empty string, all same"]),
    ("coding", "Graphs", "any", 4,
     "Given a grid of '1's (land) and '0's (water), count the number of islands. How would you solve it and what is the complexity?",
     ["DFS or BFS flood fill", "mark visited cells", "O(rows*cols) time", "recursion depth risk, iterative alternative",
      "union-find alternative"]),
    ("coding", "Big-O Analysis", "any", 2,
     "How do you analyze the time and space complexity of your code? What happens with 10 million items?",
     ["count dominant operations", "consider worst and average case", "memory of auxiliary structures",
      "constant factors matter at scale", "streaming or chunking for large data"]),
    # ---------------- ML / Data
    ("technical", "Bias-Variance", "ml", 3,
     "Explain the bias-variance trade-off. How do you detect and fix overfitting?",
     ["bias is underfitting, variance is overfitting", "compare train and validation error",
      "regularization, more data, simpler model", "cross-validation", "early stopping"]),
    ("technical", "Model Evaluation", "ml", 3,
     "For an imbalanced fraud-detection dataset, which metrics would you use and why?",
     ["accuracy is misleading with imbalance", "precision, recall, F1", "PR-AUC over ROC-AUC",
      "threshold tuning by business cost", "stratified validation"]),
    ("technical", "Gradient Descent", "ml", 3,
     "How does gradient descent work, and how do Adam and SGD differ?",
     ["iteratively update parameters along negative gradient", "learning rate controls step size",
      "mini-batch SGD trades noise for speed", "Adam uses adaptive per-parameter learning rates with momentum"]),
    ("technical", "Transformers", "ml", 4,
     "Explain how self-attention works in a Transformer.",
     ["queries, keys and values", "scaled dot-product attention", "multi-head attention",
      "positional encodings", "quadratic cost in sequence length"]),
    ("system_design", "ML System Design", "ml", 4,
     "Design a recommendation system for an e-commerce marketplace.",
     ["candidate generation and ranking stages", "features and data pipelines", "offline and online evaluation",
      "cold start", "serving latency and monitoring drift"]),
    ("technical", "SQL Analytics", "data", 3,
     "How would you compute 7-day retention by signup cohort in SQL?",
     ["define cohort by signup date", "join activity events", "date difference filtering",
      "group by cohort", "window functions or conditional aggregation"]),
    ("technical", "A/B Testing", "data", 3,
     "How do you design and analyze an A/B test? What can go wrong?",
     ["define hypothesis and primary metric", "power analysis and sample size", "randomization unit",
      "statistical significance and confidence intervals", "peeking, novelty effect, SRM"]),
    # ---------------- DevOps
    ("technical", "Docker", "devops", 2,
     "What is the difference between a container and a virtual machine? How do you make Docker images small and secure?",
     ["containers share the host kernel", "VMs virtualize hardware", "multi-stage builds", "minimal base images",
      "non-root user and no secrets in layers"]),
    ("technical", "Kubernetes", "devops", 4,
     "Explain Pods, Deployments and Services in Kubernetes. How does a rolling update work?",
     ["pod is smallest deployable unit", "deployment manages replica sets", "service provides stable networking",
      "rolling update with maxSurge and maxUnavailable", "readiness probes gate traffic"]),
    ("technical", "CI/CD", "devops", 3,
     "Describe a CI/CD pipeline you would build for a web service.",
     ["build and test on every commit", "artifact versioning", "staging environment", "automated deploy with rollback",
      "secrets management"]),
    ("technical", "Networking", "devops", 3,
     "What happens during a TLS handshake, and how does a load balancer terminate TLS?",
     ["client hello and server hello", "certificate verification", "key exchange", "session keys",
      "TLS termination at L7 load balancer"]),
    ("debugging", "Incident Response", "devops", 3,
     "Production is down at 3 AM. Walk me through your first 15 minutes.",
     ["acknowledge and communicate", "check dashboards and alerts", "mitigate first (rollback, failover)",
      "find root cause after recovery", "blameless postmortem"]),
    # ---------------- QA / Product
    ("technical", "Test Strategy", "qa", 3,
     "How would you build a test strategy for a new payment feature?",
     ["test pyramid", "risk-based prioritization", "boundary and negative cases", "automation of regression",
      "test data and environments"]),
    ("technical", "Product Prioritization", "product", 3,
     "You have ten feature requests and capacity for two. How do you decide?",
     ["tie to goals and metrics", "frameworks like RICE", "user research and data", "cost of delay",
      "communicate trade-offs to stakeholders"]),
    # ---------------- Behavioral / HR (any)
    ("behavioral", "Conflict", "any", 2,
     "Tell me about a time you disagreed with a teammate or manager. What did you do?",
     ["concrete situation", "your specific actions", "listened and used data", "outcome and what you learned"]),
    ("behavioral", "Failure", "any", 2,
     "Tell me about a project that failed or a mistake you made. What did you learn?",
     ["honest ownership", "concrete details", "actions to recover", "lesson applied later"]),
    ("behavioral", "Ownership", "any", 3,
     "Describe a situation where you took ownership of a problem outside your direct responsibility.",
     ["situation and why it mattered", "initiative taken", "stakeholders involved", "measurable result"]),
    ("behavioral", "Deadlines", "any", 2,
     "Tell me about a time you had to deliver under a tight deadline. How did you prioritize?",
     ["scope negotiation", "prioritization method", "communication of risks", "result and quality trade-offs"]),
    ("hr", "Motivation", "any", 1,
     "Why are you interested in this role and this company?",
     ["specific knowledge about the company", "link to own experience", "career goals alignment"]),
    ("hr", "Career Goals", "any", 1,
     "Where do you see yourself in two to three years?",
     ["realistic growth path", "skills to develop", "connection to the role"]),
    ("project_deep_dive", "Project Deep Dive", "any", 3,
     "Tell me about the most technically challenging project on your CV. What was your role and the hardest problem?",
     ["clear context and goal", "personal contribution", "technical decisions and trade-offs",
      "measurable result", "what you would do differently"]),
]

# family -> level -> category weights (sum to 1)
BLUEPRINTS: dict[str, dict[str, dict[str, float]]] = {
    "frontend": {
        "junior": {"technical": 0.5, "coding": 0.2, "behavioral": 0.1, "hr": 0.1, "project_deep_dive": 0.1},
        "middle": {"technical": 0.45, "coding": 0.15, "architecture": 0.1, "system_design": 0.05, "behavioral": 0.1, "project_deep_dive": 0.1, "hr": 0.05},
        "senior": {"technical": 0.35, "coding": 0.1, "architecture": 0.15, "system_design": 0.15, "behavioral": 0.15, "project_deep_dive": 0.1},
    },
    "backend": {
        "junior": {"technical": 0.5, "coding": 0.2, "behavioral": 0.1, "hr": 0.1, "project_deep_dive": 0.1},
        "middle": {"technical": 0.4, "coding": 0.15, "system_design": 0.15, "debugging": 0.05, "behavioral": 0.1, "project_deep_dive": 0.1, "hr": 0.05},
        "senior": {"technical": 0.3, "coding": 0.1, "system_design": 0.25, "debugging": 0.05, "behavioral": 0.15, "project_deep_dive": 0.15},
    },
    "ml": {
        "junior": {"technical": 0.55, "coding": 0.2, "behavioral": 0.1, "hr": 0.05, "project_deep_dive": 0.1},
        "middle": {"technical": 0.45, "coding": 0.15, "system_design": 0.15, "behavioral": 0.1, "project_deep_dive": 0.15},
        "senior": {"technical": 0.35, "coding": 0.1, "system_design": 0.25, "behavioral": 0.15, "project_deep_dive": 0.15},
    },
    "devops": {
        "junior": {"technical": 0.55, "debugging": 0.15, "behavioral": 0.1, "hr": 0.1, "project_deep_dive": 0.1},
        "middle": {"technical": 0.45, "debugging": 0.15, "system_design": 0.15, "behavioral": 0.1, "project_deep_dive": 0.15},
        "senior": {"technical": 0.35, "debugging": 0.15, "system_design": 0.25, "behavioral": 0.1, "project_deep_dive": 0.15},
    },
    "generic": {
        "junior": {"technical": 0.45, "coding": 0.15, "behavioral": 0.15, "hr": 0.1, "project_deep_dive": 0.15},
        "middle": {"technical": 0.4, "coding": 0.1, "system_design": 0.1, "behavioral": 0.15, "project_deep_dive": 0.15, "hr": 0.1},
        "senior": {"technical": 0.3, "system_design": 0.2, "behavioral": 0.2, "project_deep_dive": 0.2, "hr": 0.1},
    },
}
FAMILY_ALIASES = {"fullstack": "backend", "data": "ml", "mobile": "frontend", "qa": "generic", "product": "generic",
                  "analyst": "generic", "other": "generic"}

ROLES = [
    ("frontend-engineer", "Frontend Engineer", "frontend"),
    ("backend-engineer", "Backend Engineer", "backend"),
    ("fullstack-engineer", "Full-stack Engineer", "fullstack"),
    ("ml-engineer", "ML Engineer", "ml"),
    ("data-scientist", "Data Scientist", "ml"),
    ("data-engineer", "Data Engineer", "data"),
    ("data-analyst", "Data Analyst", "data"),
    ("devops-engineer", "DevOps / Cloud Engineer", "devops"),
    ("qa-engineer", "QA Engineer", "qa"),
    ("product-manager", "Product Manager", "product"),
]

PLANS = [
    {"code": "free", "name": "Free", "prices": {"KZT": 0, "USD": 0}, "sort": 0,
     "limits": {"interviews": 1, "resume_analyses": 2, "job_analyses": 2, "training_answers": 15},
     "features": ["limited_cv_analysis", "one_mock_interview", "readiness_score"]},
    {"code": "pro", "name": "Pro", "prices": {"KZT": 4990, "USD": 12}, "sort": 1,
     "limits": {"interviews": 30, "resume_analyses": 20, "job_analyses": 30, "training_answers": -1},
     "features": ["cv_analyzer", "jd_matching", "error_memory", "personalized_training", "system_design", "coding", "voice"]},
    {"code": "premium", "name": "Premium", "prices": {"KZT": 9990, "USD": 24}, "sort": 2,
     "limits": {"interviews": -1, "resume_analyses": -1, "job_analyses": -1, "training_answers": -1},
     "features": ["everything_in_pro", "advanced_analytics", "company_specific_prep", "priority_processing", "expert_review_addon"]},
]

# Public, verifiable facts only (name, site, industry). Interview notes stay empty until sourced.
COMPANIES = [
    ("Kaspi.kz", "KZ", "https://kaspi.kz", "Fintech / e-commerce"),
    ("Freedom Holding", "KZ", "https://ffin.kz", "Fintech / brokerage"),
    ("Halyk Bank", "KZ", "https://halykbank.kz", "Banking"),
    ("Kolesa Group", "KZ", "https://kolesa.group", "Classifieds / marketplaces"),
    ("Chocofamily", "KZ", "https://chocofamily.kz", "E-commerce / food tech"),
    ("Beeline Kazakhstan", "KZ", "https://beeline.kz", "Telecom"),
    ("EPAM Kazakhstan", "KZ", "https://www.epam.com", "IT services"),
    ("Google", "US", "https://careers.google.com", "Technology"),
    ("Amazon", "US", "https://amazon.jobs", "Technology / e-commerce"),
]
