// UI dictionary. `en` defines the keys; ru and kk must cover every key (enforced by the type).

export const en = {
  "brand": "OfferReady",
  "nav.dashboard": "Dashboard",
  "nav.resume": "Resume",
  "nav.jobs": "Vacancies",
  "nav.interviews": "Interviews",
  "nav.weaknesses": "Weak spots",
  "nav.training": "Training",
  "nav.pricing": "Pricing",
  "nav.profile": "Profile",
  "nav.admin": "Admin",
  "nav.logout": "Log out",
  "nav.login": "Log in",
  "nav.start": "Start free interview",

  "landing.title": "Practice for the interview you actually want.",
  "landing.lead": "Upload your resume, add the vacancy, and sit a realistic AI interview that pushes back like a real interviewer. Then fix exactly what went wrong.",
  "landing.cta": "Start free interview",
  "landing.secondary": "See pricing",
  "landing.steps.title": "From resume to ready, in one loop",
  "landing.step1": "Upload your resume",
  "landing.step1.d": "We find what an interviewer will ask about every line of it.",
  "landing.step2": "Add a vacancy",
  "landing.step2.d": "See your match, the gaps, and the likely interview stages.",
  "landing.step3": "Take a real AI interview",
  "landing.step3.d": "Follow-ups, doubts and harder questions when you do well.",
  "landing.step4": "Fix your weaknesses",
  "landing.step4.d": "Every mistake is remembered and trained until it's gone.",
  "landing.step5": "Get interview-ready",
  "landing.step5.d": "A readiness score that weighs what this role actually tests.",
  "landing.demo.q": "You wrote that you reduced the bundle size by 35%. How did you find what to cut?",
  "landing.demo.a": "We used code splitting and lazy loading for the heavy pages.",
  "landing.demo.fu": "That's what you did. How did you know those pages were the problem?",
  "landing.demo.a2": "I ran the bundle analyzer and saw the charts library loaded on every route…",
  "landing.demo.note": "Follow-up: shallow answer → asked to go deeper",
  "landing.promise": "We don't promise offers. We help you prepare systematically and see your readiness honestly.",
  "landing.footer": "Made in Almaty for engineers everywhere.",

  "auth.login.title": "Welcome back",
  "auth.register.title": "Create your account",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.name": "Name",
  "auth.login": "Log in",
  "auth.register": "Create account",
  "auth.noAccount": "No account yet?",
  "auth.haveAccount": "Already have an account?",
  "auth.google": "Continue with Google",
  "auth.passwordHint": "At least 8 characters",

  "onb.title": "Let's set your target",
  "onb.lead": "Start with your resume and the vacancy. We'll fill in the rest — you only correct it.",
  "onb.step.resume": "Resume",
  "onb.step.job": "Vacancy",
  "onb.step.check": "Check details",
  "onb.done": "Go to dashboard",
  "onb.skipJob": "I don't have a vacancy yet",

  "resume.title": "Resume analysis",
  "resume.upload": "Upload PDF or DOCX",
  "resume.orPaste": "or paste the text",
  "resume.analyze": "Analyze resume",
  "resume.analyzing": "Reading your resume…",
  "resume.score": "Resume score",
  "resume.ats": "ATS",
  "resume.technical": "Technical profile",
  "resume.impact": "Impact",
  "resume.clarity": "Clarity",
  "resume.experience": "Experience",
  "resume.technologies": "Technologies",
  "resume.questions": "What an interviewer will probably ask you",
  "resume.missing": "Missing information",
  "resume.suspicious": "Claims to be ready to defend",
  "resume.achievements": "Measurable impact",
  "resume.seniority": "Seniority",
  "resume.years": "Years of experience",
  "resume.empty": "Upload your resume to see how an interviewer will read it.",
  "resume.replace": "Upload a new version",

  "jobs.title": "Vacancies",
  "jobs.add": "Add vacancy",
  "jobs.empty": "Add the vacancy you're preparing for. Matching starts immediately.",
  "jobs.form.title": "Position title",
  "jobs.form.company": "Company",
  "jobs.form.description": "Job description",
  "jobs.form.descriptionHint": "Paste the full text of the vacancy",
  "jobs.form.date": "Interview date",
  "jobs.form.submit": "Analyze vacancy",
  "jobs.match": "Match",
  "jobs.strong": "Strong matches",
  "jobs.weak": "Weak matches",
  "jobs.missing": "Missing skills",
  "jobs.stages": "Likely interview stages",
  "jobs.topics": "Potential interview topics",
  "jobs.difficulty": "Expected difficulty",
  "jobs.blueprint": "Interview blueprint",
  "jobs.blueprint.d": "How the interview time is likely to be split for this role.",
  "jobs.roadmap": "Your preparation roadmap",
  "jobs.makeActive": "Prepare for this one",
  "jobs.active": "Current target",
  "jobs.startInterview": "Start interview for this vacancy",

  "iv.title": "Interviews",
  "iv.new": "New interview",
  "iv.mode": "Interview type",
  "iv.language": "Language",
  "iv.difficulty": "Starting difficulty",
  "iv.difficulty.auto": "Auto (from vacancy)",
  "iv.target": "Vacancy",
  "iv.noTarget": "No vacancy (general)",
  "iv.start": "Start interview",
  "iv.starting": "Your interviewer is preparing…",
  "iv.history": "Past interviews",
  "iv.empty": "No interviews yet. A 20–30 minute mock is the fastest way to see where you stand.",
  "iv.answer": "Your answer",
  "iv.answerHint": "Answer as you would out loud. Ctrl+Enter to send.",
  "iv.send": "Send answer",
  "iv.thinking": "Interviewer is thinking…",
  "iv.finish": "End interview",
  "iv.finishConfirm": "End now? Answered questions will be evaluated.",
  "iv.question": "Question",
  "iv.of": "of",
  "iv.followup": "Follow-up",
  "iv.stage": "Stage",
  "iv.diff": "Difficulty",
  "iv.timer": "Time",
  "iv.voice": "Dictate",
  "iv.voiceStop": "Stop",
  "iv.voiceUnsupported": "Voice input isn't supported in this browser",
  "iv.completed": "Interview complete",
  "iv.viewReport": "View report",
  "iv.retest": "Retake this interview",
  "iv.status.in_progress": "In progress",
  "iv.status.completed": "Completed",
  "iv.status.abandoned": "Abandoned",
  "iv.continue": "Continue",

  "rep.title": "Interview report",
  "rep.overall": "Interview score",
  "rep.readiness": "Readiness after this interview",
  "rep.dimensions": "Breakdown",
  "rep.strengths": "Strengths",
  "rep.weaknesses": "Weaknesses",
  "rep.recommendations": "Recommendations",
  "rep.example.best": "Best answer",
  "rep.example.worst": "Weakest answer",
  "rep.topics": "Questions by topic",
  "rep.followups": "follow-ups",
  "rep.retest": "retest",
  "rep.attempts": "Attempts on this interview",
  "rep.transcript": "Transcript",
  "rep.prev": "Previous attempt",
  "rep.training": "Open training plan",
  "rep.missed": "Missed",

  "dim.technical_knowledge": "Technical knowledge",
  "dim.problem_solving": "Problem solving",
  "dim.communication": "Communication",
  "dim.system_design": "System design",
  "dim.coding": "Coding",
  "dim.behavioral": "Behavioral",
  "dim.confidence": "Confidence",
  "dim.depth": "Depth",
  "dim.accuracy": "Accuracy",

  "cat.technical": "Technical",
  "cat.coding": "Coding",
  "cat.system_design": "System design",
  "cat.project_deep_dive": "Project deep dive",
  "cat.behavioral": "Behavioral",
  "cat.hr": "HR",
  "cat.communication": "Communication",
  "cat.architecture": "Architecture",
  "cat.debugging": "Debugging",
  "cat.situational": "Situational",
  "cat.domain": "Domain",

  "mode.technical": "Technical",
  "mode.coding": "Coding",
  "mode.system_design": "System design",
  "mode.behavioral": "Behavioral",
  "mode.hr": "HR",
  "mode.recruiter_screening": "Recruiter screening",
  "mode.project_deep_dive": "Project deep dive",
  "mode.ml": "ML",
  "mode.frontend": "Frontend",
  "mode.backend": "Backend",
  "mode.devops": "DevOps",
  "mode.mixed": "Mixed (full loop)",

  "st.READY": "Ready",
  "st.ALMOST_READY": "Almost ready",
  "st.NEEDS_WORK": "Needs work",
  "st.NOT_READY": "Not ready",

  "sev.low": "Low",
  "sev.medium": "Medium",
  "sev.high": "High",
  "sev.critical": "Critical",
  "wk.status.open": "Open",
  "wk.status.improving": "Improving",
  "wk.status.resolved": "Resolved",

  "dash.readiness": "Interview readiness",
  "dash.confidence": "Confidence of estimate",
  "dash.conf.low": "low — practise more for an accurate score",
  "dash.conf.medium": "medium",
  "dash.conf.high": "high",
  "dash.target": "Current target",
  "dash.noTarget": "No vacancy yet",
  "dash.upcoming": "Interview in",
  "dash.days": "days",
  "dash.today": "today",
  "dash.latest": "Latest mock interview",
  "dash.weakest": "Weakest skills",
  "dash.progress": "Readiness over time",
  "dash.training": "Recommended training",
  "dash.applications": "Applications",
  "dash.risks": "Your biggest risks before the interview",
  "dash.nba": "Next best action",
  "dash.categories": "By category",
  "dash.noData": "No data yet",
  "nba.upload_resume": "Upload your resume",
  "nba.add_job": "Add the vacancy you're targeting",
  "nba.start_interview": "Take a mock interview",
  "nba.do_training": "Continue training",
  "nba.retest": "Retest a weak spot",
  "nba.keep_sharp": "Keep sharp with a mixed interview",
  "nba.go": "Start",
  "risk.weakness": "Recurring mistake",
  "risk.untested": "Not practised yet",
  "risk.category": "Low score",
  "risk.missing_skill": "Required, not in your resume",

  "wk.title": "My interview weaknesses",
  "wk.lead": "Every mistake is remembered. Each one is retested until it's resolved.",
  "wk.empty": "No weaknesses recorded yet. They appear after your first interview.",
  "wk.attempts": "Attempts",
  "wk.first": "First score",
  "wk.current": "Current score",
  "wk.original": "Your answer",
  "wk.correct": "Correct concept",
  "wk.why": "Why the answer was weak",
  "wk.exercise": "Recommended exercise",
  "wk.nextRetest": "Next retest",
  "wk.question": "Question",
  "wk.filter.all": "All",
  "wk.filter.active": "Active",
  "wk.filter.resolved": "Resolved",

  "tr.title": "Training plan",
  "tr.lead": "Built from your weak spots. Each day ends with a check that updates your readiness.",
  "tr.empty": "No plan yet. Finish an interview or generate a plan now.",
  "tr.generate": "Generate plan",
  "tr.day": "Day",
  "tr.questions": "questions",
  "tr.case": "case",
  "tr.submit": "Check answer",
  "tr.score": "Score",
  "tr.done": "Done",
  "tr.feedback": "Feedback",
  "tr.yourAnswer": "Your answer",

  "price.title": "Plans",
  "price.lead": "Start free. Upgrade when you want unlimited practice.",
  "price.month": "/ month",
  "price.current": "Current plan",
  "price.choose": "Choose",
  "price.free": "Free",
  "price.limits.interviews": "Mock interviews per month",
  "price.limits.resume_analyses": "Resume analyses",
  "price.limits.job_analyses": "Vacancy analyses",
  "price.limits.training_answers": "Training answers",
  "price.unlimited": "Unlimited",
  "price.feat.limited_cv_analysis": "Resume analysis",
  "price.feat.one_mock_interview": "One mock interview",
  "price.feat.readiness_score": "Readiness score",
  "price.feat.cv_analyzer": "Resume analyzer",
  "price.feat.jd_matching": "Vacancy matching",
  "price.feat.error_memory": "Error memory",
  "price.feat.personalized_training": "Personalized training",
  "price.feat.system_design": "System design interviews",
  "price.feat.coding": "Coding interviews",
  "price.feat.voice": "Voice answers",
  "price.feat.everything_in_pro": "Everything in Pro",
  "price.feat.advanced_analytics": "Advanced analytics",
  "price.feat.company_specific_prep": "Company-specific preparation",
  "price.feat.priority_processing": "Priority processing",
  "price.feat.expert_review_addon": "Human expert review (add-on)",
  "price.quota": "You've used your plan's limit for this month.",
  "price.upgrade": "Upgrade",
  "price.sandbox.title": "Test payment",
  "price.sandbox.lead": "This is a sandbox checkout. No money is charged.",
  "price.sandbox.pay": "Confirm test payment",
  "price.success": "Your plan is active.",

  "prof.title": "Profile",
  "prof.desiredRole": "Desired role",
  "prof.level": "Level",
  "prof.stack": "Current stack",
  "prof.stackHint": "Comma-separated",
  "prof.company": "Target company",
  "prof.date": "Interview date",
  "prof.language": "Interview language",
  "prof.uiLanguage": "Interface language",
  "prof.interviewType": "Interview type",
  "prof.save": "Save changes",
  "prof.saved": "Changes saved",
  "prof.plan": "Plan",
  "prof.usage": "Usage this month",
  "prof.privacy": "Your data",
  "prof.export": "Download my data",
  "prof.delete": "Delete account",
  "prof.deleteConfirm": "Delete your account and all data permanently?",
  "prof.cancelPlan": "Cancel subscription",

  "admin.title": "Admin",
  "admin.overview": "Overview",
  "admin.users": "Users",
  "admin.ai": "AI usage",
  "admin.failures": "Failed generations",
  "admin.prompts": "Prompts",
  "admin.questions": "Questions",
  "admin.plans": "Plans",
  "admin.payments": "Payments",
  "admin.companies": "Companies",
  "admin.markReviewed": "Mark reviewed",
  "admin.activate": "Activate",
  "admin.newVersion": "Save as new version",
  "admin.makeAdmin": "Make admin",
  "admin.disable": "Disable",
  "admin.enable": "Enable",
  "admin.add": "Add",

  "common.loading": "Loading…",
  "common.error": "Something went wrong. Try again.",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.back": "Back",
  "common.next": "Next",
  "common.of100": "/ 100",
  "common.theme": "Toggle theme",
  "common.none": "None",
  "common.junior": "Junior",
  "common.middle": "Middle",
  "common.senior": "Senior",
} as const;

export type DictKey = keyof typeof en;
export type Dict = Record<DictKey, string>;
