import type { Dict } from "./dict";

export const ru: Dict = {
  "brand": "OfferReady",
  "nav.dashboard": "Главная",
  "nav.resume": "Резюме",
  "nav.jobs": "Вакансии",
  "nav.interviews": "Интервью",
  "nav.weaknesses": "Слабые места",
  "nav.training": "Тренировка",
  "nav.pricing": "Тарифы",
  "nav.profile": "Профиль",
  "nav.admin": "Админка",
  "nav.logout": "Выйти",
  "nav.login": "Войти",
  "nav.start": "Пройти интервью бесплатно",

  "landing.title": "Тренируйтесь к тому интервью, которое вам действительно нужно.",
  "landing.lead": "Загрузите резюме, добавьте вакансию и пройдите реалистичное AI-интервью, где интервьюер переспрашивает и сомневается, как настоящий. Потом исправьте именно то, что пошло не так.",
  "landing.cta": "Пройти интервью бесплатно",
  "landing.secondary": "Тарифы",
  "landing.steps.title": "От резюме до готовности — один цикл",
  "landing.step1": "Загрузите резюме",
  "landing.step1.d": "Покажем, о чём интервьюер спросит по каждой строке.",
  "landing.step2": "Добавьте вакансию",
  "landing.step2.d": "Совпадение, пробелы и вероятные этапы интервью.",
  "landing.step3": "Пройдите настоящее AI-интервью",
  "landing.step3.d": "Уточняющие вопросы, сомнения и усложнение, когда вы отвечаете хорошо.",
  "landing.step4": "Закройте слабые места",
  "landing.step4.d": "Каждая ошибка запоминается и тренируется, пока не исчезнет.",
  "landing.step5": "Станьте готовы к интервью",
  "landing.step5.d": "Оценка готовности, взвешенная по тому, что реально проверяют на этой роли.",
  "landing.demo.q": "Вы пишете, что уменьшили бандл на 35%. Как вы поняли, что именно резать?",
  "landing.demo.a": "Мы сделали code splitting и lazy loading для тяжёлых страниц.",
  "landing.demo.fu": "Это то, что вы сделали. А как вы узнали, что проблема именно в этих страницах?",
  "landing.demo.a2": "Я запустил bundle analyzer и увидел, что библиотека графиков грузится на каждом роуте…",
  "landing.demo.note": "Уточнение: поверхностный ответ → просьба копнуть глубже",
  "landing.promise": "Мы не обещаем оффер. Мы помогаем системно подготовиться и честно увидеть свою готовность.",
  "landing.footer": "Сделано в Алматы для инженеров везде.",

  "auth.login.title": "С возвращением",
  "auth.register.title": "Создайте аккаунт",
  "auth.email": "Email",
  "auth.password": "Пароль",
  "auth.name": "Имя",
  "auth.login": "Войти",
  "auth.register": "Создать аккаунт",
  "auth.noAccount": "Ещё нет аккаунта?",
  "auth.haveAccount": "Уже есть аккаунт?",
  "auth.google": "Продолжить с Google",
  "auth.passwordHint": "Не меньше 8 символов",

  "onb.title": "Определим вашу цель",
  "onb.lead": "Начните с резюме и вакансии. Остальное заполним сами — вам останется только поправить.",
  "onb.step.resume": "Резюме",
  "onb.step.job": "Вакансия",
  "onb.step.check": "Проверка данных",
  "onb.done": "Перейти на главную",
  "onb.skipJob": "Вакансии пока нет",

  "resume.title": "Анализ резюме",
  "resume.upload": "Загрузить PDF или DOCX",
  "resume.orPaste": "или вставьте текст",
  "resume.analyze": "Проанализировать резюме",
  "resume.analyzing": "Читаем ваше резюме…",
  "resume.score": "Оценка резюме",
  "resume.ats": "ATS",
  "resume.technical": "Технический профиль",
  "resume.impact": "Результаты",
  "resume.clarity": "Ясность",
  "resume.experience": "Опыт",
  "resume.technologies": "Технологии",
  "resume.questions": "О чём вас, скорее всего, спросит интервьюер",
  "resume.missing": "Чего не хватает",
  "resume.suspicious": "Утверждения, которые придётся защищать",
  "resume.achievements": "Измеримые результаты",
  "resume.seniority": "Уровень",
  "resume.years": "Лет опыта",
  "resume.empty": "Загрузите резюме, чтобы увидеть его глазами интервьюера.",
  "resume.replace": "Загрузить новую версию",

  "jobs.title": "Вакансии",
  "jobs.add": "Добавить вакансию",
  "jobs.empty": "Добавьте вакансию, к которой готовитесь. Сравнение начнётся сразу.",
  "jobs.form.title": "Название позиции",
  "jobs.form.company": "Компания",
  "jobs.form.description": "Описание вакансии",
  "jobs.form.descriptionHint": "Вставьте полный текст вакансии",
  "jobs.form.date": "Дата интервью",
  "jobs.form.submit": "Проанализировать вакансию",
  "jobs.match": "Совпадение",
  "jobs.strong": "Сильные совпадения",
  "jobs.weak": "Слабые совпадения",
  "jobs.missing": "Недостающие навыки",
  "jobs.stages": "Вероятные этапы интервью",
  "jobs.topics": "Возможные темы интервью",
  "jobs.difficulty": "Ожидаемая сложность",
  "jobs.blueprint": "Карта интервью",
  "jobs.blueprint.d": "Как, скорее всего, распределится время интервью на этой роли.",
  "jobs.roadmap": "Ваш план подготовки",
  "jobs.makeActive": "Готовиться к этой",
  "jobs.active": "Текущая цель",
  "jobs.startInterview": "Начать интервью по этой вакансии",

  "iv.title": "Интервью",
  "iv.new": "Новое интервью",
  "iv.mode": "Тип интервью",
  "iv.language": "Язык",
  "iv.difficulty": "Стартовая сложность",
  "iv.difficulty.auto": "Авто (по вакансии)",
  "iv.target": "Вакансия",
  "iv.noTarget": "Без вакансии (общее)",
  "iv.start": "Начать интервью",
  "iv.starting": "Интервьюер готовится…",
  "iv.history": "Прошлые интервью",
  "iv.empty": "Интервью ещё не было. 20–30 минут мок-интервью — самый быстрый способ понять свой уровень.",
  "iv.answer": "Ваш ответ",
  "iv.answerHint": "Отвечайте так, как сказали бы вслух. Ctrl+Enter — отправить.",
  "iv.send": "Отправить ответ",
  "iv.thinking": "Интервьюер думает…",
  "iv.finish": "Завершить интервью",
  "iv.finishConfirm": "Завершить сейчас? Отвеченные вопросы будут оценены.",
  "iv.question": "Вопрос",
  "iv.of": "из",
  "iv.followup": "Уточнение",
  "iv.stage": "Этап",
  "iv.diff": "Сложность",
  "iv.timer": "Время",
  "iv.voice": "Надиктовать",
  "iv.voiceStop": "Стоп",
  "iv.voiceUnsupported": "Голосовой ввод не поддерживается в этом браузере",
  "iv.completed": "Интервью завершено",
  "iv.viewReport": "Открыть отчёт",
  "iv.retest": "Пройти повторно",
  "iv.status.in_progress": "Идёт",
  "iv.status.completed": "Завершено",
  "iv.status.abandoned": "Прервано",
  "iv.continue": "Продолжить",

  "rep.title": "Отчёт по интервью",
  "rep.overall": "Оценка интервью",
  "rep.readiness": "Готовность после интервью",
  "rep.dimensions": "Разбор",
  "rep.strengths": "Сильные стороны",
  "rep.weaknesses": "Слабые стороны",
  "rep.recommendations": "Рекомендации",
  "rep.example.best": "Лучший ответ",
  "rep.example.worst": "Самый слабый ответ",
  "rep.topics": "Вопросы по темам",
  "rep.followups": "уточн.",
  "rep.retest": "повтор",
  "rep.attempts": "Попытки этого интервью",
  "rep.transcript": "Расшифровка",
  "rep.prev": "Прошлая попытка",
  "rep.training": "Открыть план тренировок",
  "rep.missed": "Упущено",

  "dim.technical_knowledge": "Технические знания",
  "dim.problem_solving": "Решение задач",
  "dim.communication": "Коммуникация",
  "dim.system_design": "System design",
  "dim.coding": "Кодинг",
  "dim.behavioral": "Поведенческие",
  "dim.confidence": "Уверенность",
  "dim.depth": "Глубина",
  "dim.accuracy": "Точность",

  "cat.technical": "Технические",
  "cat.coding": "Кодинг",
  "cat.system_design": "System design",
  "cat.project_deep_dive": "Разбор проектов",
  "cat.behavioral": "Поведенческие",
  "cat.hr": "HR",
  "cat.communication": "Коммуникация",
  "cat.architecture": "Архитектура",
  "cat.debugging": "Отладка",
  "cat.situational": "Ситуационные",
  "cat.domain": "Предметная область",

  "mode.technical": "Техническое",
  "mode.coding": "Кодинг",
  "mode.system_design": "System design",
  "mode.behavioral": "Поведенческое",
  "mode.hr": "HR",
  "mode.recruiter_screening": "Скрининг с рекрутером",
  "mode.project_deep_dive": "Разбор проектов",
  "mode.ml": "ML",
  "mode.frontend": "Frontend",
  "mode.backend": "Backend",
  "mode.devops": "DevOps",
  "mode.mixed": "Смешанное (полный цикл)",

  "st.READY": "Готов",
  "st.ALMOST_READY": "Почти готов",
  "st.NEEDS_WORK": "Нужна работа",
  "st.NOT_READY": "Не готов",

  "sev.low": "Низкая",
  "sev.medium": "Средняя",
  "sev.high": "Высокая",
  "sev.critical": "Критичная",
  "wk.status.open": "Открыто",
  "wk.status.improving": "Улучшается",
  "wk.status.resolved": "Закрыто",

  "dash.readiness": "Готовность к интервью",
  "dash.confidence": "Точность оценки",
  "dash.conf.low": "низкая — потренируйтесь ещё для точной оценки",
  "dash.conf.medium": "средняя",
  "dash.conf.high": "высокая",
  "dash.target": "Текущая цель",
  "dash.noTarget": "Вакансии пока нет",
  "dash.upcoming": "Интервью через",
  "dash.days": "дн.",
  "dash.today": "сегодня",
  "dash.latest": "Последнее мок-интервью",
  "dash.weakest": "Самые слабые навыки",
  "dash.progress": "Готовность во времени",
  "dash.training": "Рекомендуемая тренировка",
  "dash.applications": "Отклики",
  "dash.risks": "Ваши 3 главных риска перед интервью",
  "dash.nba": "Следующий лучший шаг",
  "dash.categories": "По категориям",
  "dash.noData": "Пока нет данных",
  "nba.upload_resume": "Загрузите резюме",
  "nba.add_job": "Добавьте целевую вакансию",
  "nba.start_interview": "Пройдите мок-интервью",
  "nba.do_training": "Продолжите тренировку",
  "nba.retest": "Перепроверьте слабое место",
  "nba.keep_sharp": "Поддерживайте форму смешанным интервью",
  "nba.go": "Начать",
  "risk.weakness": "Повторяющаяся ошибка",
  "risk.untested": "Ещё не тренировали",
  "risk.category": "Низкая оценка",
  "risk.missing_skill": "Требуется, но нет в резюме",

  "wk.title": "Мои слабые места на интервью",
  "wk.lead": "Каждая ошибка запоминается и перепроверяется, пока не будет закрыта.",
  "wk.empty": "Слабых мест пока нет. Они появятся после первого интервью.",
  "wk.attempts": "Попыток",
  "wk.first": "Первая оценка",
  "wk.current": "Текущая оценка",
  "wk.original": "Ваш ответ",
  "wk.correct": "Как правильно",
  "wk.why": "Почему ответ слабый",
  "wk.exercise": "Рекомендуемое упражнение",
  "wk.nextRetest": "Следующая проверка",
  "wk.question": "Вопрос",
  "wk.filter.all": "Все",
  "wk.filter.active": "Активные",
  "wk.filter.resolved": "Закрытые",

  "tr.title": "План тренировок",
  "tr.lead": "Собран из ваших слабых мест. Каждый день заканчивается проверкой, которая обновляет готовность.",
  "tr.empty": "Плана пока нет. Пройдите интервью или сгенерируйте план сейчас.",
  "tr.generate": "Сгенерировать план",
  "tr.day": "День",
  "tr.questions": "вопр.",
  "tr.case": "кейс",
  "tr.submit": "Проверить ответ",
  "tr.score": "Оценка",
  "tr.done": "Готово",
  "tr.feedback": "Обратная связь",
  "tr.yourAnswer": "Ваш ответ",

  "price.title": "Тарифы",
  "price.lead": "Начните бесплатно. Перейдите на платный, когда захотите тренироваться без ограничений.",
  "price.month": "/ мес",
  "price.current": "Текущий тариф",
  "price.choose": "Выбрать",
  "price.free": "Бесплатно",
  "price.limits.interviews": "Мок-интервью в месяц",
  "price.limits.resume_analyses": "Анализов резюме",
  "price.limits.job_analyses": "Анализов вакансий",
  "price.limits.training_answers": "Ответов в тренировках",
  "price.unlimited": "Без ограничений",
  "price.feat.limited_cv_analysis": "Анализ резюме",
  "price.feat.one_mock_interview": "Одно мок-интервью",
  "price.feat.readiness_score": "Оценка готовности",
  "price.feat.cv_analyzer": "Анализатор резюме",
  "price.feat.jd_matching": "Сравнение с вакансией",
  "price.feat.error_memory": "Память ошибок",
  "price.feat.personalized_training": "Персональные тренировки",
  "price.feat.system_design": "System design интервью",
  "price.feat.coding": "Кодинг-интервью",
  "price.feat.voice": "Голосовые ответы",
  "price.feat.everything_in_pro": "Всё из Pro",
  "price.feat.advanced_analytics": "Расширенная аналитика",
  "price.feat.company_specific_prep": "Подготовка под конкретную компанию",
  "price.feat.priority_processing": "Приоритетная обработка",
  "price.feat.expert_review_addon": "Разбор с экспертом (опция)",
  "price.quota": "Лимит вашего тарифа на этот месяц исчерпан.",
  "price.upgrade": "Улучшить тариф",
  "price.sandbox.title": "Тестовая оплата",
  "price.sandbox.lead": "Это тестовая оплата. Деньги не списываются.",
  "price.sandbox.pay": "Подтвердить тестовую оплату",
  "price.success": "Тариф активирован.",

  "prof.title": "Профиль",
  "prof.desiredRole": "Желаемая роль",
  "prof.level": "Уровень",
  "prof.stack": "Текущий стек",
  "prof.stackHint": "Через запятую",
  "prof.company": "Целевая компания",
  "prof.date": "Дата интервью",
  "prof.language": "Язык интервью",
  "prof.uiLanguage": "Язык интерфейса",
  "prof.interviewType": "Тип интервью",
  "prof.save": "Сохранить изменения",
  "prof.saved": "Изменения сохранены",
  "prof.plan": "Тариф",
  "prof.usage": "Использовано в этом месяце",
  "prof.privacy": "Ваши данные",
  "prof.export": "Скачать мои данные",
  "prof.delete": "Удалить аккаунт",
  "prof.deleteConfirm": "Удалить аккаунт и все данные навсегда?",
  "prof.cancelPlan": "Отменить подписку",

  "admin.title": "Админка",
  "admin.overview": "Обзор",
  "admin.users": "Пользователи",
  "admin.ai": "Использование AI",
  "admin.failures": "Неудачные генерации",
  "admin.prompts": "Промпты",
  "admin.questions": "Вопросы",
  "admin.plans": "Тарифы",
  "admin.payments": "Платежи",
  "admin.companies": "Компании",
  "admin.markReviewed": "Отметить просмотренным",
  "admin.activate": "Активировать",
  "admin.newVersion": "Сохранить новой версией",
  "admin.makeAdmin": "Сделать админом",
  "admin.disable": "Отключить",
  "admin.enable": "Включить",
  "admin.add": "Добавить",

  "common.loading": "Загрузка…",
  "common.error": "Что-то пошло не так. Попробуйте ещё раз.",
  "common.save": "Сохранить",
  "common.cancel": "Отмена",
  "common.back": "Назад",
  "common.next": "Далее",
  "common.of100": "/ 100",
  "common.theme": "Сменить тему",
  "common.none": "Нет",
  "common.junior": "Junior",
  "common.middle": "Middle",
  "common.senior": "Senior",
};
