import type { Dict } from "./dict";

export const kk: Dict = {
  "brand": "OfferReady",
  "nav.dashboard": "Басты бет",
  "nav.resume": "Түйіндеме",
  "nav.jobs": "Вакансиялар",
  "nav.interviews": "Сұхбаттар",
  "nav.weaknesses": "Әлсіз тұстар",
  "nav.training": "Жаттығу",
  "nav.pricing": "Тарифтер",
  "nav.profile": "Профиль",
  "nav.admin": "Әкімші",
  "nav.logout": "Шығу",
  "nav.login": "Кіру",
  "nav.start": "Тегін сұхбаттан өту",

  "landing.title": "Өзіңізге шын керек сұхбатқа дайындалыңыз.",
  "landing.lead": "Түйіндемені жүктеп, вакансияны қосыңыз да, нағыз интервьюер сияқты қайта сұрайтын және күмәнданатын AI-сұхбаттан өтіңіз. Содан кейін дәл қате кеткен жерді түзетіңіз.",
  "landing.cta": "Тегін сұхбаттан өту",
  "landing.secondary": "Тарифтер",
  "landing.steps.title": "Түйіндемеден дайындыққа дейін — бір цикл",
  "landing.step1": "Түйіндемені жүктеңіз",
  "landing.step1.d": "Әр жол бойынша интервьюер не сұрайтынын көрсетеміз.",
  "landing.step2": "Вакансияны қосыңыз",
  "landing.step2.d": "Сәйкестік, олқылықтар және сұхбаттың ықтимал кезеңдері.",
  "landing.step3": "Нағыз AI-сұхбаттан өтіңіз",
  "landing.step3.d": "Қосымша сұрақтар, күмән және жақсы жауап берсеңіз — қиындау сұрақтар.",
  "landing.step4": "Әлсіз тұстарды жабыңыз",
  "landing.step4.d": "Әр қате есте сақталады және жойылғанша жаттықтырылады.",
  "landing.step5": "Сұхбатқа дайын болыңыз",
  "landing.step5.d": "Осы рөлде шын тексерілетін нәрсеге қарай есептелген дайындық бағасы.",
  "landing.demo.q": "Бандлды 35%-ға кішірейттім деп жазыпсыз. Нені алып тастау керегін қалай түсіндіңіз?",
  "landing.demo.a": "Ауыр беттер үшін code splitting және lazy loading жасадық.",
  "landing.demo.fu": "Бұл не істегеніңіз. Ал мәселе дәл сол беттерде екенін қалай білдіңіз?",
  "landing.demo.a2": "Bundle analyzer іске қосып, графиктер кітапханасы әр роутта жүктелетінін көрдім…",
  "landing.demo.note": "Қосымша сұрақ: үстірт жауап → тереңірек түсіндіру сұралды",
  "landing.promise": "Біз оффер уәде етпейміз. Жүйелі дайындалуға және дайындығыңызды адал бағалауға көмектесеміз.",
  "landing.footer": "Алматыда, барлық инженерлер үшін жасалған.",

  "auth.login.title": "Қош келдіңіз",
  "auth.register.title": "Аккаунт жасаңыз",
  "auth.email": "Email",
  "auth.password": "Құпиясөз",
  "auth.name": "Аты",
  "auth.login": "Кіру",
  "auth.register": "Аккаунт жасау",
  "auth.noAccount": "Аккаунтыңыз жоқ па?",
  "auth.haveAccount": "Аккаунтыңыз бар ма?",
  "auth.google": "Google арқылы жалғастыру",
  "auth.passwordHint": "Кемінде 8 таңба",

  "onb.title": "Мақсатыңызды анықтайық",
  "onb.lead": "Түйіндеме мен вакансиядан бастаңыз. Қалғанын өзіміз толтырамыз — сізге тек түзету қалады.",
  "onb.step.resume": "Түйіндеме",
  "onb.step.job": "Вакансия",
  "onb.step.check": "Деректерді тексеру",
  "onb.done": "Басты бетке өту",
  "onb.skipJob": "Әзірге вакансия жоқ",

  "resume.title": "Түйіндеме талдауы",
  "resume.upload": "PDF немесе DOCX жүктеу",
  "resume.orPaste": "немесе мәтінді қойыңыз",
  "resume.analyze": "Түйіндемені талдау",
  "resume.analyzing": "Түйіндемеңізді оқып жатырмыз…",
  "resume.score": "Түйіндеме бағасы",
  "resume.ats": "ATS",
  "resume.technical": "Техникалық профиль",
  "resume.impact": "Нәтижелер",
  "resume.clarity": "Анықтық",
  "resume.experience": "Тәжірибе",
  "resume.technologies": "Технологиялар",
  "resume.questions": "Интервьюер сізден не сұрауы мүмкін",
  "resume.missing": "Не жетіспейді",
  "resume.suspicious": "Қорғауға тура келетін тұжырымдар",
  "resume.achievements": "Өлшенетін нәтижелер",
  "resume.seniority": "Деңгей",
  "resume.years": "Тәжірибе жылдары",
  "resume.empty": "Түйіндемені интервьюер көзімен көру үшін оны жүктеңіз.",
  "resume.replace": "Жаңа нұсқасын жүктеу",

  "jobs.title": "Вакансиялар",
  "jobs.add": "Вакансия қосу",
  "jobs.empty": "Дайындалып жатқан вакансияны қосыңыз. Салыстыру бірден басталады.",
  "jobs.form.title": "Лауазым атауы",
  "jobs.form.company": "Компания",
  "jobs.form.description": "Вакансия сипаттамасы",
  "jobs.form.descriptionHint": "Вакансияның толық мәтінін қойыңыз",
  "jobs.form.date": "Сұхбат күні",
  "jobs.form.submit": "Вакансияны талдау",
  "jobs.match": "Сәйкестік",
  "jobs.strong": "Күшті сәйкестіктер",
  "jobs.weak": "Әлсіз сәйкестіктер",
  "jobs.missing": "Жетіспейтін дағдылар",
  "jobs.stages": "Сұхбаттың ықтимал кезеңдері",
  "jobs.topics": "Сұхбаттың ықтимал тақырыптары",
  "jobs.difficulty": "Күтілетін күрделілік",
  "jobs.blueprint": "Сұхбат картасы",
  "jobs.blueprint.d": "Бұл рөлде сұхбат уақыты қалай бөлінуі мүмкін.",
  "jobs.roadmap": "Дайындық жоспарыңыз",
  "jobs.makeActive": "Осыған дайындалу",
  "jobs.active": "Ағымдағы мақсат",
  "jobs.startInterview": "Осы вакансия бойынша сұхбат бастау",

  "iv.title": "Сұхбаттар",
  "iv.new": "Жаңа сұхбат",
  "iv.mode": "Сұхбат түрі",
  "iv.language": "Тіл",
  "iv.difficulty": "Бастапқы күрделілік",
  "iv.difficulty.auto": "Авто (вакансия бойынша)",
  "iv.target": "Вакансия",
  "iv.noTarget": "Вакансиясыз (жалпы)",
  "iv.start": "Сұхбатты бастау",
  "iv.starting": "Интервьюер дайындалып жатыр…",
  "iv.history": "Өткен сұхбаттар",
  "iv.empty": "Әзірге сұхбат болған жоқ. 20–30 минуттық мок-сұхбат — деңгейіңізді білудің ең жылдам жолы.",
  "iv.answer": "Сіздің жауабыңыз",
  "iv.answerHint": "Дауыстап айтатындай жауап беріңіз. Ctrl+Enter — жіберу.",
  "iv.send": "Жауапты жіберу",
  "iv.thinking": "Интервьюер ойланып жатыр…",
  "iv.finish": "Сұхбатты аяқтау",
  "iv.finishConfirm": "Қазір аяқтайсыз ба? Жауап берілген сұрақтар бағаланады.",
  "iv.question": "Сұрақ",
  "iv.of": "/",
  "iv.followup": "Қосымша сұрақ",
  "iv.stage": "Кезең",
  "iv.diff": "Күрделілік",
  "iv.timer": "Уақыт",
  "iv.voice": "Дауыспен айту",
  "iv.voiceStop": "Тоқтату",
  "iv.voiceUnsupported": "Бұл браузерде дауыспен енгізу қолдау таппайды",
  "iv.completed": "Сұхбат аяқталды",
  "iv.viewReport": "Есепті ашу",
  "iv.retest": "Қайта өту",
  "iv.status.in_progress": "Жүріп жатыр",
  "iv.status.completed": "Аяқталды",
  "iv.status.abandoned": "Үзілді",
  "iv.continue": "Жалғастыру",

  "rep.title": "Сұхбат есебі",
  "rep.overall": "Сұхбат бағасы",
  "rep.readiness": "Сұхбаттан кейінгі дайындық",
  "rep.dimensions": "Талдау",
  "rep.strengths": "Күшті жақтары",
  "rep.weaknesses": "Әлсіз жақтары",
  "rep.recommendations": "Ұсыныстар",
  "rep.example.best": "Ең жақсы жауап",
  "rep.example.worst": "Ең әлсіз жауап",
  "rep.topics": "Тақырыптар бойынша сұрақтар",
  "rep.followups": "қосымша",
  "rep.retest": "қайталау",
  "rep.attempts": "Осы сұхбаттағы әрекеттер",
  "rep.transcript": "Транскрипт",
  "rep.prev": "Алдыңғы әрекет",
  "rep.training": "Жаттығу жоспарын ашу",
  "rep.missed": "Қалып кетті",

  "dim.technical_knowledge": "Техникалық білім",
  "dim.problem_solving": "Есеп шығару",
  "dim.communication": "Коммуникация",
  "dim.system_design": "System design",
  "dim.coding": "Кодинг",
  "dim.behavioral": "Мінез-құлық",
  "dim.confidence": "Сенімділік",
  "dim.depth": "Тереңдік",
  "dim.accuracy": "Дәлдік",

  "cat.technical": "Техникалық",
  "cat.coding": "Кодинг",
  "cat.system_design": "System design",
  "cat.project_deep_dive": "Жобаларды талдау",
  "cat.behavioral": "Мінез-құлық",
  "cat.hr": "HR",
  "cat.communication": "Коммуникация",
  "cat.architecture": "Архитектура",
  "cat.debugging": "Жөндеу",
  "cat.situational": "Жағдаяттық",
  "cat.domain": "Пәндік сала",

  "mode.technical": "Техникалық",
  "mode.coding": "Кодинг",
  "mode.system_design": "System design",
  "mode.behavioral": "Мінез-құлық",
  "mode.hr": "HR",
  "mode.recruiter_screening": "Рекрутермен скрининг",
  "mode.project_deep_dive": "Жобаларды талдау",
  "mode.ml": "ML",
  "mode.frontend": "Frontend",
  "mode.backend": "Backend",
  "mode.devops": "DevOps",
  "mode.mixed": "Аралас (толық цикл)",

  "st.READY": "Дайын",
  "st.ALMOST_READY": "Дайын дерлік",
  "st.NEEDS_WORK": "Жұмыс керек",
  "st.NOT_READY": "Дайын емес",

  "sev.low": "Төмен",
  "sev.medium": "Орташа",
  "sev.high": "Жоғары",
  "sev.critical": "Сыни",
  "wk.status.open": "Ашық",
  "wk.status.improving": "Жақсаруда",
  "wk.status.resolved": "Жабылды",

  "dash.readiness": "Сұхбатқа дайындық",
  "dash.confidence": "Бағаның дәлдігі",
  "dash.conf.low": "төмен — дәл баға үшін көбірек жаттығыңыз",
  "dash.conf.medium": "орташа",
  "dash.conf.high": "жоғары",
  "dash.target": "Ағымдағы мақсат",
  "dash.noTarget": "Әзірге вакансия жоқ",
  "dash.upcoming": "Сұхбатқа дейін",
  "dash.days": "күн",
  "dash.today": "бүгін",
  "dash.latest": "Соңғы мок-сұхбат",
  "dash.weakest": "Ең әлсіз дағдылар",
  "dash.progress": "Уақыт бойынша дайындық",
  "dash.training": "Ұсынылатын жаттығу",
  "dash.applications": "Өтінімдер",
  "dash.risks": "Сұхбат алдындағы 3 басты тәуекел",
  "dash.nba": "Келесі ең жақсы қадам",
  "dash.categories": "Санаттар бойынша",
  "dash.noData": "Әзірге дерек жоқ",
  "nba.upload_resume": "Түйіндемені жүктеңіз",
  "nba.add_job": "Мақсатты вакансияны қосыңыз",
  "nba.start_interview": "Мок-сұхбаттан өтіңіз",
  "nba.do_training": "Жаттығуды жалғастырыңыз",
  "nba.retest": "Әлсіз тұсты қайта тексеріңіз",
  "nba.keep_sharp": "Аралас сұхбатпен формада болыңыз",
  "nba.go": "Бастау",
  "risk.weakness": "Қайталанатын қате",
  "risk.untested": "Әлі жаттықпаған",
  "risk.category": "Төмен баға",
  "risk.missing_skill": "Талап етіледі, түйіндемеде жоқ",

  "wk.title": "Сұхбаттағы әлсіз тұстарым",
  "wk.lead": "Әр қате есте сақталады және жабылғанша қайта тексеріледі.",
  "wk.empty": "Әзірге әлсіз тұстар жоқ. Олар алғашқы сұхбаттан кейін пайда болады.",
  "wk.attempts": "Әрекеттер",
  "wk.first": "Алғашқы баға",
  "wk.current": "Ағымдағы баға",
  "wk.original": "Сіздің жауабыңыз",
  "wk.correct": "Дұрыс ұғым",
  "wk.why": "Жауап неге әлсіз",
  "wk.exercise": "Ұсынылатын жаттығу",
  "wk.nextRetest": "Келесі тексеру",
  "wk.question": "Сұрақ",
  "wk.filter.all": "Барлығы",
  "wk.filter.active": "Белсенді",
  "wk.filter.resolved": "Жабылған",

  "tr.title": "Жаттығу жоспары",
  "tr.lead": "Әлсіз тұстарыңыздан құралған. Әр күн дайындықты жаңартатын тексерумен аяқталады.",
  "tr.empty": "Әзірге жоспар жоқ. Сұхбаттан өтіңіз немесе жоспарды қазір жасаңыз.",
  "tr.generate": "Жоспар жасау",
  "tr.day": "Күн",
  "tr.questions": "сұрақ",
  "tr.case": "кейс",
  "tr.submit": "Жауапты тексеру",
  "tr.score": "Баға",
  "tr.done": "Дайын",
  "tr.feedback": "Кері байланыс",
  "tr.yourAnswer": "Сіздің жауабыңыз",

  "price.title": "Тарифтер",
  "price.lead": "Тегін бастаңыз. Шектеусіз жаттығу керек болғанда тарифті жаңартыңыз.",
  "price.month": "/ ай",
  "price.current": "Ағымдағы тариф",
  "price.choose": "Таңдау",
  "price.free": "Тегін",
  "price.limits.interviews": "Айына мок-сұхбат",
  "price.limits.resume_analyses": "Түйіндеме талдауы",
  "price.limits.job_analyses": "Вакансия талдауы",
  "price.limits.training_answers": "Жаттығудағы жауаптар",
  "price.unlimited": "Шектеусіз",
  "price.feat.limited_cv_analysis": "Түйіндеме талдауы",
  "price.feat.one_mock_interview": "Бір мок-сұхбат",
  "price.feat.readiness_score": "Дайындық бағасы",
  "price.feat.cv_analyzer": "Түйіндеме анализаторы",
  "price.feat.jd_matching": "Вакансиямен салыстыру",
  "price.feat.error_memory": "Қателер жады",
  "price.feat.personalized_training": "Жеке жаттығулар",
  "price.feat.system_design": "System design сұхбаттары",
  "price.feat.coding": "Кодинг сұхбаттары",
  "price.feat.voice": "Дауыстық жауаптар",
  "price.feat.everything_in_pro": "Pro-дағының бәрі",
  "price.feat.advanced_analytics": "Кеңейтілген аналитика",
  "price.feat.company_specific_prep": "Нақты компанияға дайындық",
  "price.feat.priority_processing": "Басым өңдеу",
  "price.feat.expert_review_addon": "Сарапшы талдауы (қосымша)",
  "price.quota": "Тарифіңіздің осы айға арналған лимиті таусылды.",
  "price.upgrade": "Тарифті жақсарту",
  "price.sandbox.title": "Сынақ төлемі",
  "price.sandbox.lead": "Бұл сынақ төлемі. Ақша алынбайды.",
  "price.sandbox.pay": "Сынақ төлемін растау",
  "price.success": "Тариф қосылды.",

  "prof.title": "Профиль",
  "prof.desiredRole": "Қалаған рөл",
  "prof.level": "Деңгей",
  "prof.stack": "Ағымдағы стек",
  "prof.stackHint": "Үтір арқылы",
  "prof.company": "Мақсатты компания",
  "prof.date": "Сұхбат күні",
  "prof.language": "Сұхбат тілі",
  "prof.uiLanguage": "Интерфейс тілі",
  "prof.interviewType": "Сұхбат түрі",
  "prof.save": "Өзгерістерді сақтау",
  "prof.saved": "Өзгерістер сақталды",
  "prof.plan": "Тариф",
  "prof.usage": "Осы айда пайдаланылды",
  "prof.privacy": "Сіздің деректеріңіз",
  "prof.export": "Деректерімді жүктеп алу",
  "prof.delete": "Аккаунтты жою",
  "prof.deleteConfirm": "Аккаунт пен барлық деректерді біржола жоясыз ба?",
  "prof.cancelPlan": "Жазылымнан бас тарту",

  "admin.title": "Әкімші",
  "admin.overview": "Шолу",
  "admin.users": "Пайдаланушылар",
  "admin.ai": "AI пайдалану",
  "admin.failures": "Сәтсіз генерациялар",
  "admin.prompts": "Промпттар",
  "admin.questions": "Сұрақтар",
  "admin.plans": "Тарифтер",
  "admin.payments": "Төлемдер",
  "admin.companies": "Компаниялар",
  "admin.markReviewed": "Қаралды деп белгілеу",
  "admin.activate": "Белсендіру",
  "admin.newVersion": "Жаңа нұсқа ретінде сақтау",
  "admin.makeAdmin": "Әкімші ету",
  "admin.disable": "Өшіру",
  "admin.enable": "Қосу",
  "admin.add": "Қосу",

  "common.loading": "Жүктелуде…",
  "common.error": "Бірдеңе дұрыс болмады. Қайталап көріңіз.",
  "common.save": "Сақтау",
  "common.cancel": "Болдырмау",
  "common.back": "Артқа",
  "common.next": "Әрі қарай",
  "common.of100": "/ 100",
  "common.theme": "Тақырыпты ауыстыру",
  "common.none": "Жоқ",
  "common.junior": "Junior",
  "common.middle": "Middle",
  "common.senior": "Senior",
};
